-- Continue adding remaining models for all makes
-- Jaguar models
INSERT INTO models (make_id, name) VALUES
((SELECT id FROM makes WHERE name = 'Jaguar'), 'F-Pace'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'XF'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'E-Pace'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'F-Type'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'XE'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'XJ'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'XJ-Series'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'XKR'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'XK'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'I-Pace'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'S-Type'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'E-Type'),
((SELECT id FROM makes WHERE name = 'Jaguar'), 'XJS'),

-- Jeep models
((SELECT id FROM makes WHERE name = 'Jeep'), 'Wrangler'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Grand Cherokee'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Wrangler Unlimited'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Cherokee'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Grand Cherokee L'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Compass'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Grand Wagoneer'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Gladiator'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Renegade'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Wrangler 4xe'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Commander'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Patriot'),
((SELECT id FROM makes WHERE name = 'Jeep'), 'Other'),

-- Jetour models
((SELECT id FROM makes WHERE name = 'Jetour'), 'T2'),
((SELECT id FROM makes WHERE name = 'Jetour'), 'Dashing'),
((SELECT id FROM makes WHERE name = 'Jetour'), 'T1'),
((SELECT id FROM makes WHERE name = 'Jetour'), 'X70 Plus'),
((SELECT id FROM makes WHERE name = 'Jetour'), 'X70'),
((SELECT id FROM makes WHERE name = 'Jetour'), 'X90 Plus'),
((SELECT id FROM makes WHERE name = 'Jetour'), 'X50'),
((SELECT id FROM makes WHERE name = 'Jetour'), 'T2-4DM'),
((SELECT id FROM makes WHERE name = 'Jetour'), 'X70 FL'),
((SELECT id FROM makes WHERE name = 'Jetour'), 'X70 S'),

-- Kia models
((SELECT id FROM makes WHERE name = 'Kia'), 'Sportage'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Seltos'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Sorento'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Carnival'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Pegas'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Optima'),
((SELECT id FROM makes WHERE name = 'Kia'), 'K5'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Rio'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Cerato'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Picanto'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Telluride'),
((SELECT id FROM makes WHERE name = 'Kia'), 'K3'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Soul'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Sonet'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Forte'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Sedona'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Cadenza'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Stinger'),
((SELECT id FROM makes WHERE name = 'Kia'), 'K8'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Bongo'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Carens'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Mohave'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Morning'),
((SELECT id FROM makes WHERE name = 'Kia'), 'K5 HEV'),
((SELECT id FROM makes WHERE name = 'Kia'), 'KX1'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Quoris'),
((SELECT id FROM makes WHERE name = 'Kia'), 'Ray'),

-- Lincoln models
((SELECT id FROM makes WHERE name = 'Lincoln'), 'Navigator'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'Aviator'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'MKX'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'Nautilus'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'MKC'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'Corsair'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'Continental'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'MKS'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'MKZ'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'MKT'),
((SELECT id FROM makes WHERE name = 'Lincoln'), 'Town Car');