-- Add remaining models for the last set of makes
-- Maserati models
INSERT INTO models (make_id, name) VALUES
((SELECT id FROM makes WHERE name = 'Maserati'), 'Ghibli'),
((SELECT id FROM makes WHERE name = 'Maserati'), 'Levante'),
((SELECT id FROM makes WHERE name = 'Maserati'), 'Grecale'),
((SELECT id FROM makes WHERE name = 'Maserati'), 'Quattroporte'),
((SELECT id FROM makes WHERE name = 'Maserati'), 'GranTurismo'),
((SELECT id FROM makes WHERE name = 'Maserati'), 'MC20'),
((SELECT id FROM makes WHERE name = 'Maserati'), 'GranCabrio'),
((SELECT id FROM makes WHERE name = 'Maserati'), '4200'),
((SELECT id FROM makes WHERE name = 'Maserati'), 'Spyder'),

-- Mazda models
((SELECT id FROM makes WHERE name = 'Mazda'), 'CX-5'),
((SELECT id FROM makes WHERE name = 'Mazda'), '6'),
((SELECT id FROM makes WHERE name = 'Mazda'), 'CX-9'),
((SELECT id FROM makes WHERE name = 'Mazda'), '3'),
((SELECT id FROM makes WHERE name = 'Mazda'), 'CX-3'),
((SELECT id FROM makes WHERE name = 'Mazda'), 'CX-30'),
((SELECT id FROM makes WHERE name = 'Mazda'), '2'),
((SELECT id FROM makes WHERE name = 'Mazda'), 'MX-5'),
((SELECT id FROM makes WHERE name = 'Mazda'), '3 Hatchback'),
((SELECT id FROM makes WHERE name = 'Mazda'), 'CX-60'),
((SELECT id FROM makes WHERE name = 'Mazda'), 'CX-90'),
((SELECT id FROM makes WHERE name = 'Mazda'), 'CX-7'),
((SELECT id FROM makes WHERE name = 'Mazda'), 'Pickup'),

-- MG models
((SELECT id FROM makes WHERE name = 'MG'), 'MG5'),
((SELECT id FROM makes WHERE name = 'MG'), 'ZS'),
((SELECT id FROM makes WHERE name = 'MG'), 'RX5'),
((SELECT id FROM makes WHERE name = 'MG'), 'GT'),
((SELECT id FROM makes WHERE name = 'MG'), 'HS'),
((SELECT id FROM makes WHERE name = 'MG'), 'RX8'),
((SELECT id FROM makes WHERE name = 'MG'), 'One'),
((SELECT id FROM makes WHERE name = 'MG'), 'MG 7'),
((SELECT id FROM makes WHERE name = 'MG'), 'GS'),
((SELECT id FROM makes WHERE name = 'MG'), 'ZST'),
((SELECT id FROM makes WHERE name = 'MG'), '6'),
((SELECT id FROM makes WHERE name = 'MG'), 'Whale'),
((SELECT id FROM makes WHERE name = 'MG'), 'MG3'),
((SELECT id FROM makes WHERE name = 'MG'), 'MG350'),
((SELECT id FROM makes WHERE name = 'MG'), 'MG6'),
((SELECT id FROM makes WHERE name = 'MG'), 'MGB'),
((SELECT id FROM makes WHERE name = 'MG'), 'RX9'),

-- MINI models
((SELECT id FROM makes WHERE name = 'MINI'), 'Cooper'),
((SELECT id FROM makes WHERE name = 'MINI'), 'Countryman'),
((SELECT id FROM makes WHERE name = 'MINI'), 'Clubman'),
((SELECT id FROM makes WHERE name = 'MINI'), 'Coupe'),
((SELECT id FROM makes WHERE name = 'MINI'), 'Paceman'),
((SELECT id FROM makes WHERE name = 'MINI'), 'Aceman'),
((SELECT id FROM makes WHERE name = 'MINI'), 'Cooper Clubman'),
((SELECT id FROM makes WHERE name = 'MINI'), 'Roadster'),

-- Mitsubishi models
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Pajero'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Attrage'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'L200'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'ASX'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Montero Sport'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Outlander'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Canter'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Lancer'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Xpander'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Lancer EX'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Eclipse Cross'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Mirage'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Pajero Sport'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Xpander Cross'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Galant'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Van'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Evolution'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Grandis'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), '3000GT'),
((SELECT id FROM makes WHERE name = 'Mitsubishi'), 'Eclipse'),

-- Peugeot models
((SELECT id FROM makes WHERE name = 'Peugeot'), '3008'),
((SELECT id FROM makes WHERE name = 'Peugeot'), 'Partner'),
((SELECT id FROM makes WHERE name = 'Peugeot'), 'Expert'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '308'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '2008'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '208'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '5008'),
((SELECT id FROM makes WHERE name = 'Peugeot'), 'Landtrek'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '301'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '508'),
((SELECT id FROM makes WHERE name = 'Peugeot'), 'Boxer'),
((SELECT id FROM makes WHERE name = 'Peugeot'), 'RCZ'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '207'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '408'),
((SELECT id FROM makes WHERE name = 'Peugeot'), 'Traveller'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '206'),
((SELECT id FROM makes WHERE name = 'Peugeot'), '307'),
((SELECT id FROM makes WHERE name = 'Peugeot'), 'e-2008'),
((SELECT id FROM makes WHERE name = 'Peugeot'), 'iOn');