-- Continue adding missing models for remaining makes
-- Chevrolet models
INSERT INTO models (make_id, name) VALUES
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Captiva'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Camaro'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Tahoe'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Corvette'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Silverado'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Malibu'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Cruze'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Groove'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Traverse'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Spark'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Suburban'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Trax'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Blazer'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Trailblazer'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Equinox'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Impala'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Aveo'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Camaro Convertible'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Express'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Lumina'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Sonic'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Avalanche'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Caprice'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Epica'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Bolt'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Monza'),
((SELECT id FROM makes WHERE name = 'Chevrolet'), 'Pickup'),

-- Dodge models
((SELECT id FROM makes WHERE name = 'Dodge'), 'Charger'),
((SELECT id FROM makes WHERE name = 'Dodge'), 'Challenger'),
((SELECT id FROM makes WHERE name = 'Dodge'), 'Ram'),
((SELECT id FROM makes WHERE name = 'Dodge'), 'Durango'),
((SELECT id FROM makes WHERE name = 'Dodge'), 'Nitro'),
((SELECT id FROM makes WHERE name = 'Dodge'), 'Caravan'),
((SELECT id FROM makes WHERE name = 'Dodge'), 'Neon'),
((SELECT id FROM makes WHERE name = 'Dodge'), 'Viper'),
((SELECT id FROM makes WHERE name = 'Dodge'), 'Magnum'),
((SELECT id FROM makes WHERE name = 'Dodge'), 'Van'),

-- Cadillac models
((SELECT id FROM makes WHERE name = 'Cadillac'), 'Escalade'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'ATS'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'CT5'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'XT4'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'SRX'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'XT5'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'CT4'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'CT6'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'XT6'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'CT5/Catera'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'XTR/Eldorado'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'DTS/DeVille'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'STS/Seville'),
((SELECT id FROM makes WHERE name = 'Cadillac'), 'XTS'),

-- GMC models
((SELECT id FROM makes WHERE name = 'GMC'), 'Yukon'),
((SELECT id FROM makes WHERE name = 'GMC'), 'Sierra'),
((SELECT id FROM makes WHERE name = 'GMC'), 'Terrain'),
((SELECT id FROM makes WHERE name = 'GMC'), 'Acadia'),
((SELECT id FROM makes WHERE name = 'GMC'), 'Hummer'),
((SELECT id FROM makes WHERE name = 'GMC'), 'Savana'),
((SELECT id FROM makes WHERE name = 'GMC'), 'Pickup'),
((SELECT id FROM makes WHERE name = 'GMC'), 'Canyon'),

-- Infiniti models
((SELECT id FROM makes WHERE name = 'Infiniti'), 'QX50'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'QX80'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'Q50'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'QX70'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'QX60'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'QX55'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'FX45/FX35'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'Q30'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'JX-Series'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'Q70'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'G25'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'EX35'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'G37'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'Q60'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'QX30'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'QX56'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'M-Series'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'FX50'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'G35'),
((SELECT id FROM makes WHERE name = 'Infiniti'), 'Q45');