-- Continue with remaining models
INSERT INTO models (make_id, name) VALUES
-- Mercedes-Benz
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'G-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'S-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'C-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'E-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'A-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'CLA'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'AMG'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'GLE Coupe'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'GLE-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'GLC'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'V-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'SL-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'CLS-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'GLS-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'GLC Coupe'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'G-Class Brabus'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'GLA'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'GL-Class'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'GLB'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'EQS'),
((SELECT id FROM makes WHERE name = 'Mercedes-Benz'), 'EQE'),

-- Lexus
((SELECT id FROM makes WHERE name = 'Lexus'), 'RX-Series'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'IS-Series'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'LX600'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'NX-Series'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'ES-Series'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'GX 460'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'LX570'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'LS-Series'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'GS-Series'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'LX-Series'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'UX 200'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'LM 350h'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'LC 500'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'ES HYBRID'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'UX-Series'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'RC F'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'TX'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'GX 470'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'GX 550'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'LM 300'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'RC'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'CT-Series'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'LFA'),
((SELECT id FROM makes WHERE name = 'Lexus'), 'SC-Series'),

-- Land Rover
((SELECT id FROM makes WHERE name = 'Land Rover'), 'Range Rover'),
((SELECT id FROM makes WHERE name = 'Land Rover'), 'Range Rover Sport'),
((SELECT id FROM makes WHERE name = 'Land Rover'), 'Defender'),
((SELECT id FROM makes WHERE name = 'Land Rover'), 'Range Rover Evoque'),
((SELECT id FROM makes WHERE name = 'Land Rover'), 'Range Rover Velar'),
((SELECT id FROM makes WHERE name = 'Land Rover'), 'Discovery Sport'),
((SELECT id FROM makes WHERE name = 'Land Rover'), 'Discovery'),
((SELECT id FROM makes WHERE name = 'Land Rover'), 'LR4'),
((SELECT id FROM makes WHERE name = 'Land Rover'), 'LR2'),
((SELECT id FROM makes WHERE name = 'Land Rover'), 'LR3'),

-- Porsche
((SELECT id FROM makes WHERE name = 'Porsche'), 'Carrera / 911'),
((SELECT id FROM makes WHERE name = 'Porsche'), 'Cayenne'),
((SELECT id FROM makes WHERE name = 'Porsche'), 'Macan'),
((SELECT id FROM makes WHERE name = 'Porsche'), 'Panamera'),
((SELECT id FROM makes WHERE name = 'Porsche'), 'Cayman'),
((SELECT id FROM makes WHERE name = 'Porsche'), 'Boxster'),
((SELECT id FROM makes WHERE name = 'Porsche'), 'Taycan'),
((SELECT id FROM makes WHERE name = 'Porsche'), '911'),
((SELECT id FROM makes WHERE name = 'Porsche'), '718 Spyder'),
((SELECT id FROM makes WHERE name = 'Porsche'), '918 Spyder'),
((SELECT id FROM makes WHERE name = 'Porsche'), '928'),
((SELECT id FROM makes WHERE name = 'Porsche'), '944'),
((SELECT id FROM makes WHERE name = 'Porsche'), '968'),

-- Ford
((SELECT id FROM makes WHERE name = 'Ford'), 'Mustang'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Explorer'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Edge'),
((SELECT id FROM makes WHERE name = 'Ford'), 'F-Series Pickup'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Escape'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Ecosport'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Focus'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Bronco'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Ranger'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Figo'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Expedition'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Territory'),
((SELECT id FROM makes WHERE name = 'Ford'), 'F-Series'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Transit'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Fusion'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Everest'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Taurus'),
((SELECT id FROM makes WHERE name = 'Ford'), 'GT'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Fiesta'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Shelby Cobra'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Escort'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Mustang Mach-E'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Pickup'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Crown Victoria'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Flex'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Super Duty'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Tourneo'),
((SELECT id FROM makes WHERE name = 'Ford'), 'Van');