-- Insert missing models for all makes
-- Ferrari models
INSERT INTO models (make_id, name) VALUES
((SELECT id FROM makes WHERE name = 'Ferrari'), 'Purosangue'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'SF90 Spider'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'SF90 Stradale'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '812 GTS'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'Roma'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '296 GTB'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '296 GTS'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '488 Pista'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'F8 Spider'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '812'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'F8 Tributo'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'Portofino'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '488 GTB'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '488 Pista Spider'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '12i Cilindri'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'GTC4 Lusso'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '360'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '458 Italia'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '488 Spider'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '812 Superfast'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'California T'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'F430'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '458 Spider'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '612 Scaglietti'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'California'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'GTC4 Lusso T'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'F12'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'LaFerrari'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '512'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'F12 Berlinetta'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'Testarossa'),
((SELECT id FROM makes WHERE name = 'Ferrari'), '599 GTB'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'Daytona'),
((SELECT id FROM makes WHERE name = 'Ferrari'), 'FF'),

-- Honda models
((SELECT id FROM makes WHERE name = 'Honda'), 'Accord'),
((SELECT id FROM makes WHERE name = 'Honda'), 'Civic'),
((SELECT id FROM makes WHERE name = 'Honda'), 'CR-V'),
((SELECT id FROM makes WHERE name = 'Honda'), 'City'),
((SELECT id FROM makes WHERE name = 'Honda'), 'HR-V'),
((SELECT id FROM makes WHERE name = 'Honda'), 'Odyssey'),
((SELECT id FROM makes WHERE name = 'Honda'), 'Pilot'),
((SELECT id FROM makes WHERE name = 'Honda'), 'ZR-V'),
((SELECT id FROM makes WHERE name = 'Honda'), 'Jazz'),
((SELECT id FROM makes WHERE name = 'Honda'), 'MR-V'),
((SELECT id FROM makes WHERE name = 'Honda'), 'S2000'),
((SELECT id FROM makes WHERE name = 'Honda'), 'Crosstour'),
((SELECT id FROM makes WHERE name = 'Honda'), 'ENP2'),
((SELECT id FROM makes WHERE name = 'Honda'), 'ENS1'),

-- Hyundai models
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Tucson'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Elantra'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Sonata'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Santa Fe'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Accent'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Creta'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Palisade'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Staria'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'H1'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Veloster'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Kona'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Azera'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Grand i10'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Venue'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'i10'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Genesis'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Grand Santa Fe'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'i30'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Avante'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Grandeur'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Porter'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Stargazer'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Centennial'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'H 100'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'i20'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Ioniq'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Santa Cruz'),
((SELECT id FROM makes WHERE name = 'Hyundai'), 'Terracan'),

-- Tesla models
((SELECT id FROM makes WHERE name = 'Tesla'), 'Model 3'),
((SELECT id FROM makes WHERE name = 'Tesla'), 'Model Y'),
((SELECT id FROM makes WHERE name = 'Tesla'), 'Model X'),
((SELECT id FROM makes WHERE name = 'Tesla'), 'Cybertruck'),
((SELECT id FROM makes WHERE name = 'Tesla'), 'Model S');