-- Add final set of models for remaining makes
-- Renault models
INSERT INTO models (make_id, name) VALUES
((SELECT id FROM makes WHERE name = 'Renault'), 'Duster'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Koleos'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Megane'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Symbol'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Captur'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Dokker'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Fluence'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Master'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Express Van'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Talisman'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Alpine A110'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Arkana'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Clio'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Safrane'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Samsung'),
((SELECT id FROM makes WHERE name = 'Renault'), 'Zoe'),

-- Rolls-Royce models
((SELECT id FROM makes WHERE name = 'Rolls-Royce'), 'Cullinan'),
((SELECT id FROM makes WHERE name = 'Rolls-Royce'), 'Ghost'),
((SELECT id FROM makes WHERE name = 'Rolls-Royce'), 'Wraith'),
((SELECT id FROM makes WHERE name = 'Rolls-Royce'), 'Phantom'),
((SELECT id FROM makes WHERE name = 'Rolls-Royce'), 'Spectre'),
((SELECT id FROM makes WHERE name = 'Rolls-Royce'), 'Dawn'),

-- Suzuki models
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Jimny'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Swift'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Ciaz'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Dzire'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Baleno'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Grand Vitara'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Ertiga'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Fronx'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Vitara'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Celerio'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'APV Van'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'SX4'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Eeco'),
((SELECT id FROM makes WHERE name = 'Suzuki'), 'Kizashi'),

-- Volkswagen models
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Golf'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Tiguan'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Teramont'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Touareg'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Passat'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'T-Roc'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'ID.4'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Jetta'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Beetle'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'ID.6'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'CC'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Scirocco'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Polo'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Transporter'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Amarok'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Arteon'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Atlas'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Crafter'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Eos'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'ID.7'),
((SELECT id FROM makes WHERE name = 'Volkswagen'), 'Multivan'),

-- Volvo models
((SELECT id FROM makes WHERE name = 'Volvo'), 'XC60'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'XC90'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'S90'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'XC40'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'V-Class'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'S60'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'Other'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'C-Class'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'C40'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'S40'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'S80'),
((SELECT id FROM makes WHERE name = 'Volvo'), 'XC40 Recharge'),

-- GAC models
((SELECT id FROM makes WHERE name = 'GAC'), 'GS8'),
((SELECT id FROM makes WHERE name = 'GAC'), 'GS3'),
((SELECT id FROM makes WHERE name = 'GAC'), 'EMKOO'),
((SELECT id FROM makes WHERE name = 'GAC'), 'EMPOW'),
((SELECT id FROM makes WHERE name = 'GAC'), 'Aion Hyper'),
((SELECT id FROM makes WHERE name = 'GAC'), 'GA4'),
((SELECT id FROM makes WHERE name = 'GAC'), 'EMZOOM'),
((SELECT id FROM makes WHERE name = 'GAC'), 'GA8'),
((SELECT id FROM makes WHERE name = 'GAC'), 'GN6'),
((SELECT id FROM makes WHERE name = 'GAC'), 'GN8'),
((SELECT id FROM makes WHERE name = 'GAC'), 'GS5'),
((SELECT id FROM makes WHERE name = 'GAC'), 'GA6'),
((SELECT id FROM makes WHERE name = 'GAC'), 'M8'),
((SELECT id FROM makes WHERE name = 'GAC'), 'S7'),
((SELECT id FROM makes WHERE name = 'GAC'), 'Aion Y');