-- Clear existing data
DELETE FROM trims;
DELETE FROM models;
DELETE FROM makes;

-- Insert Makes
INSERT INTO makes (name) VALUES
('Audi'),
('BMW'),
('Bentley'),
('BYD'),
('Cadillac'),
('Chevrolet'),
('Dodge'),
('Ferrari'),
('Ford'),
('GAC'),
('GMC'),
('Honda'),
('Hyundai'),
('Infiniti'),
('Jaguar'),
('Jeep'),
('Jetour'),
('Kia'),
('Land Rover'),
('Lexus'),
('Lincoln'),
('Maserati'),
('Mazda'),
('Mercedes-Benz'),
('MG'),
('MINI'),
('Mitsubishi'),
('Nissan'),
('Peugeot'),
('Porsche'),
('Renault'),
('Rolls-Royce'),
('Suzuki'),
('Tesla'),
('Toyota'),
('Volkswagen'),
('Volvo');

-- Insert Models for Audi
INSERT INTO models (make_id, name) VALUES
((SELECT id FROM makes WHERE name = 'Audi'), 'Q5'),
((SELECT id FROM makes WHERE name = 'Audi'), 'Q7'),
((SELECT id FROM makes WHERE name = 'Audi'), 'A3'),
((SELECT id FROM makes WHERE name = 'Audi'), 'A8'),
((SELECT id FROM makes WHERE name = 'Audi'), 'A6'),
((SELECT id FROM makes WHERE name = 'Audi'), 'Q8'),
((SELECT id FROM makes WHERE name = 'Audi'), 'Q4'),
((SELECT id FROM makes WHERE name = 'Audi'), 'A4'),
((SELECT id FROM makes WHERE name = 'Audi'), 'A5'),
((SELECT id FROM makes WHERE name = 'Audi'), 'Q3'),
((SELECT id FROM makes WHERE name = 'Audi'), 'TT'),
((SELECT id FROM makes WHERE name = 'Audi'), 'A7'),
((SELECT id FROM makes WHERE name = 'Audi'), 'R8'),
((SELECT id FROM makes WHERE name = 'Audi'), 'SQ5'),
((SELECT id FROM makes WHERE name = 'Audi'), 'S5'),
((SELECT id FROM makes WHERE name = 'Audi'), 'e-tron'),
((SELECT id FROM makes WHERE name = 'Audi'), 'S3'),
((SELECT id FROM makes WHERE name = 'Audi'), 'S8'),
((SELECT id FROM makes WHERE name = 'Audi'), 'RSQ3'),
((SELECT id FROM makes WHERE name = 'Audi'), 'SQ8'),
((SELECT id FROM makes WHERE name = 'Audi'), 'Q2'),
((SELECT id FROM makes WHERE name = 'Audi'), 'A1'),
((SELECT id FROM makes WHERE name = 'Audi'), 'RS e-tron'),
((SELECT id FROM makes WHERE name = 'Audi'), 'SQ7');

-- Insert Models for BMW
INSERT INTO models (make_id, name) VALUES
((SELECT id FROM makes WHERE name = 'BMW'), 'X5'),
((SELECT id FROM makes WHERE name = 'BMW'), '5-Series'),
((SELECT id FROM makes WHERE name = 'BMW'), 'X6'),
((SELECT id FROM makes WHERE name = 'BMW'), '7-Series'),
((SELECT id FROM makes WHERE name = 'BMW'), '3-Series'),
((SELECT id FROM makes WHERE name = 'BMW'), '4-Series'),
((SELECT id FROM makes WHERE name = 'BMW'), 'X7'),
((SELECT id FROM makes WHERE name = 'BMW'), '2-Series'),
((SELECT id FROM makes WHERE name = 'BMW'), 'X4'),
((SELECT id FROM makes WHERE name = 'BMW'), 'X1'),
((SELECT id FROM makes WHERE name = 'BMW'), 'M4'),
((SELECT id FROM makes WHERE name = 'BMW'), 'X3'),
((SELECT id FROM makes WHERE name = 'BMW'), 'X2'),
((SELECT id FROM makes WHERE name = 'BMW'), 'M5'),
((SELECT id FROM makes WHERE name = 'BMW'), '6-Series'),
((SELECT id FROM makes WHERE name = 'BMW'), '8-Series'),
((SELECT id FROM makes WHERE name = 'BMW'), '1-Series'),
((SELECT id FROM makes WHERE name = 'BMW'), 'M3'),
((SELECT id FROM makes WHERE name = 'BMW'), 'Z4'),
((SELECT id FROM makes WHERE name = 'BMW'), 'XM'),
((SELECT id FROM makes WHERE name = 'BMW'), 'iX'),
((SELECT id FROM makes WHERE name = 'BMW'), 'M8'),
((SELECT id FROM makes WHERE name = 'BMW'), 'M2'),
((SELECT id FROM makes WHERE name = 'BMW'), 'iX1'),
((SELECT id FROM makes WHERE name = 'BMW'), 'i5'),
((SELECT id FROM makes WHERE name = 'BMW'), 'i4'),
((SELECT id FROM makes WHERE name = 'BMW'), 'iX3'),
((SELECT id FROM makes WHERE name = 'BMW'), 'i3'),
((SELECT id FROM makes WHERE name = 'BMW'), 'M6'),
((SELECT id FROM makes WHERE name = 'BMW'), 'i7'),
((SELECT id FROM makes WHERE name = 'BMW'), 'i8'),
((SELECT id FROM makes WHERE name = 'BMW'), 'iX2'),
((SELECT id FROM makes WHERE name = 'BMW'), 'M1'),
((SELECT id FROM makes WHERE name = 'BMW'), 'Z3'),
((SELECT id FROM makes WHERE name = 'BMW'), 'Z8');

-- Insert Models for remaining makes (continuing with next batch...)
INSERT INTO models (make_id, name) VALUES
-- Bentley
((SELECT id FROM makes WHERE name = 'Bentley'), 'Continental'),
((SELECT id FROM makes WHERE name = 'Bentley'), 'Bentayga'),
((SELECT id FROM makes WHERE name = 'Bentley'), 'Flying Spur'),
((SELECT id FROM makes WHERE name = 'Bentley'), 'Mulsanne'),
((SELECT id FROM makes WHERE name = 'Bentley'), 'Arnage'),
((SELECT id FROM makes WHERE name = 'Bentley'), 'Azure'),
((SELECT id FROM makes WHERE name = 'Bentley'), 'Brooklands'),

-- BYD
((SELECT id FROM makes WHERE name = 'BYD'), 'Leopard 8'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Leopard 5'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Song Plus'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Leopard Titanium 3'),
((SELECT id FROM makes WHERE name = 'BYD'), 'HAN'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Leopard'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Song L'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Seal'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Qin L'),
((SELECT id FROM makes WHERE name = 'BYD'), 'e2'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Tang'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Qin Plus'),
((SELECT id FROM makes WHERE name = 'BYD'), 'ATTO 3'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Seagull'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Song Pro'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Yuan up'),
((SELECT id FROM makes WHERE name = 'BYD'), 'SEALION'),
((SELECT id FROM makes WHERE name = 'BYD'), 'BYD'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Destroyer 05'),
((SELECT id FROM makes WHERE name = 'BYD'), 'Dolphin'),
((SELECT id FROM makes WHERE name = 'BYD'), 'XIA');

-- Due to SQL length limits, I'll continue with the most important models
-- Toyota models
INSERT INTO models (make_id, name) VALUES
((SELECT id FROM makes WHERE name = 'Toyota'), 'Land Cruiser'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Prado'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Hilux'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Rav 4'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Corolla'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Yaris'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Camry'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Fortuner'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Hiace'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Highlander'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'FJ Cruiser'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Corolla Cross'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Rush'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Land Cruiser 76 series'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Tundra'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Land Cruiser 79 series'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'C-HR'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Land Cruiser 70'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Coaster'),
((SELECT id FROM makes WHERE name = 'Toyota'), '4Runner'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Sienna'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Raize'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Avanza'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Granvia'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Innova'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Tacoma'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Land Cruiser 71'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Sequoia'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Supra'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Crown'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Prius'),
((SELECT id FROM makes WHERE name = 'Toyota'), 'Avalon');

-- Nissan models
INSERT INTO models (make_id, name) VALUES
((SELECT id FROM makes WHERE name = 'Nissan'), 'Patrol'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Altima'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Sunny'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'X-Trail'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Kicks'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Pathfinder'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Sentra'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Xterra'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Armada'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Urvan'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Tiida'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Maxima'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Juke'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Navara'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Patrol Safari'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Rogue'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Micra'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Murano'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'GT-R'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Skyline'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Versa'),
((SELECT id FROM makes WHERE name = 'Nissan'), '370z'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Qashqai'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Super Safari'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Pickup'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Sylphy'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Titan'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Z'),
((SELECT id FROM makes WHERE name = 'Nissan'), '350Z'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Quest'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Silvia'),
((SELECT id FROM makes WHERE name = 'Nissan'), '400Z'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Magnite'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Patrol Pickup'),
((SELECT id FROM makes WHERE name = 'Nissan'), 'Van');