// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esupkobpjswkibyzhlio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzdXBrb2JwanN3a2lieXpobGlvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwOTUwMTEsImV4cCI6MjA3MDY3MTAxMX0.zvs1i7U6vhBbmmBiEzvU9y5_tQ_K_2HI2cdXFxi0-uU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});